server:
  ports: 8080

tracer:
  property: "I AM THE DEFAULT"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.111.132:3306/test?serverTimezone=UTC
    username: root
    password: Luowenlong@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true